parameters:
    log.rabbitexchange.name: 'direct-log'
    log.rabbitexchange.type: 'direct'

    rabbitMq.host: 'rabbitmq'
    rabbitMq.port: 5672
    rabbitMq.user: 'guest'
    rabbitMq.pass: 'guest'
    rabbitMq.vhost: '/'

    kafka.publisher.config:
        - metadata.broker.list: 'kafka:9092'

    kafka.consumer.config:
        - group.id: 'errorGroup'
        - enable.partition.eof: 'true'

    kafka.consumer.topicConfig:
        - auto.commit.interval.ms: '100'
        - offset.store.method: 'broker' #Set the offset store method to 'file'
        - auto.offset.reset: 'earliest' #Set where to start consuming messages when there is no initial offset in
                                        #offset store or the desired offset is out of range.
                                        #'earliest': start from the beginning


services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Module/{Rate,Subscription,Mailer}/'

    rabbitMq.connection: '@PhpAmqpLib\Connection\AMQPStreamConnection'
    rabbit.client: '@App\Broker\Rabbit\RabbitClient'
    kafka.client: '@App\Broker\Kafka\KafkaClient'
    log.rabbit.publisher: '@App\Broker\Rabbit\LogRabbitPublisher'
    log.rabbit.receiver: '@App\Broker\Rabbit\LogRabbitReceiver'
    log.kafka.publisher: '@App\Broker\Kafka\LogKafkaPublisher'
    log.kafka.receiver: '@App\Broker\Kafka\LogKafkaReceiver'
    custom.logger: '@App\Logger\CustomErrorLogger'

    PhpAmqpLib\Connection\AMQPStreamConnection:
        arguments:
            $host: '%rabbitMq.host%'
            $port: '%rabbitMq.port%'
            $user: '%rabbitMq.user%'
            $password: '%rabbitMq.pass%'

    App\Broker\Rabbit\RabbitClient:
        arguments:
            $connection: '@rabbitMq.connection'

    App\Broker\Kafka\LogKafkaPublisher:
        arguments:
            $kafkaClient: '@kafka.client'
            $kafkaConfig: '%kafka.publisher.config%'

    App\Broker\Rabbit\LogRabbitPublisher:
        arguments:
            $rabbitClient: '@rabbit.client'
            $exchangeName: '%log.rabbitexchange.name%'
            $exchangeType: '%log.rabbitexchange.type%'

    App\Broker\Rabbit\LogRabbitReceiver:
        arguments:
            $client: '@rabbit.client'
            $exchangeName: '%log.rabbitexchange.name%'
            $exchangeType: '%log.rabbitexchange.type%'

    App\Broker\Kafka\LogKafkaReceiver:
        arguments:
            $client: '@kafka.client'
            $consumerConfig: '%kafka.consumer.config%'
            $topicConfig: '%kafka.consumer.topicConfig%'
            $brokerName: 'kafka'

    App\Logger\CustomErrorLogger:
        arguments:
            $logPublisher: '@log.rabbit.publisher'
            $logPublisher2: '@log.kafka.publisher'
